#!/bin/bash

# RELOAD MONITOR SETTINGS
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# WINDOW SETTINGS
bspc config border_width 2
bspc config window_gap 12
bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#414868"
bspc config active_border_color "#7aa2f7"

# LAYOUT SETTINGS
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false

# FOCUS FOLLOWS POINTER
bspc config focus_follows_pointer true

# START SXHKD (KEYBINDINGS)
sxhkd &

# SET WALLPAPER
feh --bg-fill ~/Pictures/wallpapers/wallpaper.jpg &

# START COMPOSITOR FOR TRANSPARENCY/SHADOWS
picom &

# START POLYBAR (WE'LL SET THIS UP NEXT)
~/.config/polybar/launch.sh &

# START KITTY TERMINAL
kitty &
